#!/usr/bin/env python

#import modules
from enum import Enum, unique

#definitions for positions in a student council in Mapua University
@unique
class Position(Enum):
    PRESIDENT = 0
    VICE_PRESIDENT_INT = 1
    VICE_PRESIDENT_EXT = 2
    SECRETARY_EXECUTIVE = 3
    SECRETARY_FINANCE = 4
    SECRETARY_AUDIT = 5
    SECRETARY_LOGISTICS = 6
    SECRETARY_SCHOLARSHIP = 7
    SECRETARY_INFO_CORRESPONDENCE = 8
    SECRETARY_AMUSEMENT_RECREATION = 9
    SECRETARY_WELFARE_DEV = 10
    REPRESENTATIVE_4TH_YEAR = 11
    REPRESENTATIVE_3RD_YEAR = 12
    REPRESENTATIVE_2ND_YEAR = 13
    REPRESENTATIVE_GENERAL = 14
    REPRESENTATIVE_CSC = 15
    BUSINESS_MANAGER = 16